### PR TITLE
add clang-dev for flecstan

### PR DESCRIPTION
**Pull request by junghans**
For https://github.com/laristra/flecsi/pull/533

### CODE REVIEW

**Comment by junghans** [comment]
@staleyLANL please review!

**Review by staleyLANL — APPROVED** [review]
Looks fine.

**Comment by staleyLANL** [comment]
So these prevented the error about not finding Sema.h, correct?

**Comment by junghans** [comment]
These will make the header available in the docker image for the CI, you still want to use https://cmake.org/cmake/help/v3.0/module/CheckIncludeFile.html to check for the header.

**Pull request merged**
