### PR TITLE
Added vim as default package installed

### PR DESCRIPTION
**Pull request by ktsai7**

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by charest** [comment]
Do we need to create a `stable` branch here to fix the tests?

**Comment by charest** [comment]
@junghans Sorry i closed by accident.  Reopened

**Comment by junghans** [comment]
I think this repo deploys from master

**Comment by charest** [comment]
Okay, the CI for all the other projects is messed up I am just trying to figure out how to fix it.

**Pull request merged**
